#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Sat Mar 30 17:53:43 2019

@author: sakshirane
"""

import urllib
import urllib.request
from bs4 import BeautifulSoup
import os 

def make_soup(url):
    thepage = urllib.request.urlopen(url)
    soupdata = BeautifulSoup(thepage, "html.parser")
    return soupdata



soup = make_soup("http://www.discjockey.org/top-100-songs-of-the-2000s/")
musicdatasaved = ""
for record in soup.find_all('tr'):
    musicdata = ""
    for data in record.find_all('td'):
        musicdata = musicdata + "," + data.text
    musicdatasaved = musicdatasaved + "\n" + musicdata[1:]
    
    
header = "Rank, Song, Artist, Year, Genre"
file = open(os.path.expanduser("music.csv"),"wb")
file.write(bytes(header, encoding = "ascii", errors = "ignore"))
file.write(bytes(musicdatasaved, encoding = "ascii", errors = "ignore"))  
